env:
  max_time_steps: 500000
model:
  rnn_units: 800
  use_rnn: false
ppo:
  annealing: true
  clipping_parameter: 0.1
  discount: 0.99
  entropy_coeff: 0.01
  gae_parameter: 0.95
  horizon: 128
  lr: 0.00025
  num_actors: 8
  num_epochs: 3
  num_minibatch: 4
  vf_coeff: 1
